local M = {}

M.prompts = {
  Explain = "Explain how the selected code works. Describe the main flow, important functions, inputs, outputs, and any non-obvious behavior.",
  Review = "Review the selected code and suggest improvements for readability, maintainability, performance, security, and idiomatic style. Explain the reasons behind each suggestion.",
  Tests = "Explain how the selected code works, then generate meaningful unit tests for it. Cover normal cases, edge cases, and possible error cases. Use the appropriate testing framework for the detected language.",
  Refactor = "Refactor the selected code to improve clarity, readability, maintainability, and idiomatic style. Preserve the existing behavior unless a bug is clearly present. Briefly explain the changes.",
  FixCode = "Fix the selected code so it works as intended. Identify the issue, explain the cause, and provide the corrected version. Preserve the original intent and avoid unnecessary changes.",
  FixError = "Explain the error in the following text, identify the likely cause, and provide a clear solution. Include corrected code or commands when applicable.",
  BetterNamings = "Suggest better names for the selected variables, functions, classes, or files. Prefer clear, idiomatic, and intention-revealing names. Explain the most important suggestions briefly.",
  Documentation = "Generate clear and concise documentation for the selected code. Use the idiomatic documentation format for the detected programming language. Include purpose, parameters, return values, errors/exceptions, side effects, and usage notes when helpful.",
  GoDocs = "Generate idiomatic Go doc comments for the selected Go code. Follow standard Go documentation conventions: exported identifiers should have comments that start with the identifier name. Describe what the code does, its behavior, parameters, return values, errors, side effects, and usage notes when helpful.",
  JsDocs = "Generate JSDoc comments for the selected JavaScript or TypeScript code. Include descriptions, parameters, return values, thrown errors, types, and examples when helpful.",
  DocumentationForGithub = "Generate GitHub-ready Markdown documentation for the selected code. Include an overview, usage instructions, API/reference details, examples, configuration notes, and any important caveats.",
  CreateAPost = "Create a deep, well-explained, easy-to-understand social media post about the selected code, suitable for LinkedIn. Make it engaging, educational, and slightly fun while keeping a professional tone.",
  SwaggerApiDocs = "Generate Swagger/OpenAPI documentation for the selected API. Include endpoints, methods, parameters, request bodies, responses, status codes, schemas, and examples when possible.",
  SwaggerGoDocs = "Generate Swagger/OpenAPI annotations for the selected Go API code using idiomatic Go comments, compatible with common Go Swagger tools such as swaggo/swag when possible. Include @Summary, @Description, @Tags, @Accept, @Produce, @Param, @Success, @Failure, and @Router annotations when applicable.",
  SwaggerJsDocs = "Generate JSDoc comments with Swagger/OpenAPI annotations for the selected API code. Include routes, methods, parameters, request bodies, responses, status codes, schemas, and examples when possible.",
  Summarize = "Summarize the following text clearly and concisely. Focus on the main ideas, important details, and conclusions.",
  Spelling = "Correct grammar, spelling, punctuation, and minor style issues in the following text. Preserve the original meaning and tone.",
  Wording = "Improve the grammar, wording, clarity, and flow of the following text. Preserve the original meaning, but make it sound more natural and polished.",
  Concise = "Rewrite the following text to make it more concise while preserving the key meaning, tone, and important details.",
}

M.order = {
  "Explain",
  "Review",
  "Tests",
  "Refactor",
  "FixCode",
  "FixError",
  "BetterNamings",
  "Documentation",
  "GoDocs",
  "JsDocs",
  "DocumentationForGithub",
  "CreateAPost",
  "SwaggerApiDocs",
  "SwaggerGoDocs",
  "SwaggerJsDocs",
  "Summarize",
  "Spelling",
  "Wording",
  "Concise",
}

M.bindings = {
  Explain = "e",
  Review = "r",
  Tests = "t",
  Refactor = "f",
  FixCode = "x",
  FixError = "E",
  BetterNamings = "n",
  Documentation = "d",
  GoDocs = "g",
  JsDocs = "j",
  DocumentationForGithub = "h",
  CreateAPost = "p",
  SwaggerApiDocs = "s",
  SwaggerGoDocs = "S",
  SwaggerJsDocs = "J",
  Summarize = "m",
  Spelling = "l",
  Wording = "w",
  Concise = "c",
}

M.descriptions = {
  Explain = "Explain behavior",
  Review = "Review code",
  Tests = "Generate tests",
  Refactor = "Refactor code",
  FixCode = "Fix code",
  FixError = "Explain error",
  BetterNamings = "Suggest better names",
  Documentation = "Generate documentation",
  GoDocs = "Generate Go docs",
  JsDocs = "Generate JSDoc",
  DocumentationForGithub = "Generate GitHub docs",
  CreateAPost = "Write social post",
  SwaggerApiDocs = "Generate Swagger docs",
  SwaggerGoDocs = "Generate Swagger Go annotations",
  SwaggerJsDocs = "Generate Swagger JSDoc",
  Summarize = "Summarize text",
  Spelling = "Fix spelling",
  Wording = "Improve wording",
  Concise = "Make concise",
}

return M
